<?xml version="1.0" encoding="utf-8"?><Database Name="generalDB" Class="KFDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sqlgeneralwork.database.windows.net;Initial Catalog=generalDB;Persist Security Info=True;User ID=UCLProjekt" SettingsObjectName="DataManagement.Properties.Settings" SettingsPropertyName="generalDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Colours" Member="Colours">
    <Type Name="Colour">
      <Column Name="Colour_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Colour_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Colour_Product_Colour" Member="Product_Colours" ThisKey="Colour_Id" OtherKey="Colour_Id" Type="Product_Colour" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Streetname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zipcode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phonenumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Order" Member="Orders" ThisKey="Customer_Id" OtherKey="Customer_Id" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="Employee_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phonenumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Order" Member="Orders" ThisKey="Employee_Id" OtherKey="Employee_Id" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Grips" Member="Grips">
    <Type Name="Grip">
      <Column Name="Grip_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Grip_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Grip_Product_Grip" Member="Product_Grips" ThisKey="Grip_Id" OtherKey="Grip_Id" Type="Product_Grip" />
    </Type>
  </Table>
  <Table Name="dbo.Materials" Member="Materials">
    <Type Name="Material">
      <Column Name="Material_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Material_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Material_Product_Material" Member="Product_Materials" ThisKey="Material_Id" OtherKey="Material_Id" Type="Product_Material" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="Order_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Customer_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employee_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="To_Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="To_Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="To_Phonenumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="To_Street" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="To_City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="To_Zipcode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateOfSending" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Order_Comment" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Order_Order_Product" Member="Order_Products" ThisKey="Order_Id" OtherKey="Order_Id" Type="Order_Product" />
      <Association Name="Customer_Order" Member="Customer" ThisKey="Customer_Id" OtherKey="Customer_Id" Type="Customer" IsForeignKey="true" />
      <Association Name="Employee_Order" Member="Employee" ThisKey="Employee_Id" OtherKey="Employee_Id" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Product" Member="Order_Products">
    <Type Name="Order_Product">
      <Column Name="Junction_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Order_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_Count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Product_Colour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_Material" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Product_Grip" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Order_Order_Product" Member="Order" ThisKey="Order_Id" OtherKey="Order_Id" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Order_Product" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductGroup_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Material" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Colours" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Grip" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Product_Order_Product" Member="Order_Products" ThisKey="Product_Id" OtherKey="Product_Id" Type="Order_Product" />
      <Association Name="Product_Product_Colour" Member="Product_Colours" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product_Colour" />
      <Association Name="Product_Product_Grip" Member="Product_Grips" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product_Grip" />
      <Association Name="Product_Product_Material" Member="Product_Materials" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product_Material" />
      <Association Name="ProductGroup_Product" Member="ProductGroup" ThisKey="ProductGroup_Id" OtherKey="ProductGroup_Id" Type="ProductGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Colours" Member="Product_Colours">
    <Type Name="Product_Colour">
      <Column Name="Junction_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Colour_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Colour_Product_Colour" Member="Colour" ThisKey="Colour_Id" OtherKey="Colour_Id" Type="Colour" IsForeignKey="true" />
      <Association Name="Product_Product_Colour" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Grips" Member="Product_Grips">
    <Type Name="Product_Grip">
      <Column Name="Junction_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grip_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Grip_Product_Grip" Member="Grip" ThisKey="Grip_Id" OtherKey="Grip_Id" Type="Grip" IsForeignKey="true" />
      <Association Name="Product_Product_Grip" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Materials" Member="Product_Materials">
    <Type Name="Product_Material">
      <Column Name="Junction_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Material_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Material_Product_Material" Member="Material" ThisKey="Material_Id" OtherKey="Material_Id" Type="Material" IsForeignKey="true" />
      <Association Name="Product_Product_Material" Member="Product" ThisKey="Product_Id" OtherKey="Product_Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductGroup" Member="ProductGroups">
    <Type Name="ProductGroup">
      <Column Name="ProductGroup_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductGroupName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Association Name="ProductGroup_Product" Member="Products" ThisKey="ProductGroup_Id" OtherKey="ProductGroup_Id" Type="Product" />
    </Type>
  </Table>
</Database>